export const WINE_REGIONS = [
  'Mendoza, Argentina',
  'Marlborough, New Zealand',
  'South Australia',
  'Provence, France',
  'Tuscany, Italy',
  'Napa Valley, USA',
  'Rías Baixas, Spain',
  'Piedmont, Italy',
  'Burgundy, France',
  'California, USA',
  'Mosel, Germany',
  'Rhône Valley, France',
  'Wachau, Austria',
  'Valdobbiadene, Italy',
  'Loire Valley, France',
  'Veneto, Italy',
] as const;

export const WINE_GRAPES = [
  'Malbec',
  'Sauvignon Blanc',
  'Cabernet Sauvignon',
  'Shiraz',
  'Grenache',
  'Cinsault',
  'Rolle',
  'Sangiovese',
  'Cabernet Franc',
  'Pinot Noir',
  'Merlot',
  'Petit Verdot',
  'Albariño',
  'Nebbiolo',
  'Chardonnay',
  'Riesling',
  'Mourvèdre',
  'Syrah',
  'Counoise',
  'Grüner Veltliner',
  'Glera',
  'Corvina',
  'Rondinella',
  'Oseleta',
] as const;
